// <auto-generated />
namespace Mhotivo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class changeSectionType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeSectionType));
        
        string IMigrationMetadata.Id
        {
            get { return "201502110237400_changeSectionType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
